services:
  web-api:
    image: web-api
    build: 
      dockerfile: MeasurementSystemWebAPI/Dockerfile
    ports:
      - '3500:80'
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - ./InfluxDB/db:/var/lib/influxdb2
      - ./InfluxDB/configs:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_DB=influxdb
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user 
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password 
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=init-bucket
